[package]
name = "my_staking_program"
version = "0.1.0"
edition = "2018"

[dependencies]
anchor-lang = "0.24.2"
anchor-spl = "0.24.2"  # Add this line

[lib]
crate-type = ["cdylib"]

[features]
default = ["no-entrypoint", "cpi", "custom-heap", "custom-panic", "anchor-debug"]